name: macos-autotools

on: workflow_dispatch

permissions:
  contents: read

jobs:
  cmake:
    runs-on: macos-latest

    name: macos-autotools-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Install deps
      run: |
        brew update
        brew install autoconf automake libtool pcre2 bison

    # Put brewed bison first on PATH for later steps, the default one is ancient
    - name: Use brewed bison
      run: echo "$(brew --prefix bison)/bin" >> "$GITHUB_PATH"

    - name: Bootstrap (generate configure)
      env:
        LIBTOOL: glibtool
        LIBTOOLIZE: glibtoolize
      run: |
        ./autogen.sh

    - name: Configure
      run: ./configure --prefix="${{ github.workspace }}/installmac"

    - name: Build
      run: make -j8

    - name: Install
      run: make install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: swig-macos-autotools
        path: ${{ github.workspace }}/installmac
        if-no-files-found: error
